(() => {
  const API_URL = window.CHESS_ADVISOR_API_URL || "REPLACE_WITH_AWS_LAMBDA_FUNCTION_URL";
  const launcher=document.getElementById("chatLauncher"), panel=document.getElementById("chatPanel"), close=document.getElementById("chatClose"), form=document.getElementById("chatForm"), input=document.getElementById("chatInput"), body=document.getElementById("chatBody"), status=document.getElementById("chatStatus");
  let sessionId=null;
  const starters=["Which session is right for my team?","How does chess apply to business risk?","Show me how a 60-minute session works.","What makes Prasanna credible for this topic?"];
  function addMessage(text,who){const div=document.createElement("div");div.className=`chat-msg ${who}`;div.textContent=text;body.appendChild(div);body.scrollTop=body.scrollHeight}
  function addStarters(){const wrap=document.createElement("div");wrap.className="chat-suggestions";starters.forEach(text=>{const button=document.createElement("button");button.className="chat-chip";button.type="button";button.textContent=text;button.onclick=()=>ask(text);wrap.appendChild(button)});body.appendChild(wrap)}
  async function ask(text){text=(text||"").trim();if(!text)return;if(API_URL.includes("REPLACE_WITH")){addMessage("The AWS backend has not been connected yet. Deploy the AWS stack, then set the Lambda Function URL in js/chatbot.js.","bot");return}addMessage(text,"user");input.value="";status.textContent="Thinking…";try{const res=await fetch(API_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,sessionId})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Request failed.");sessionId=data.sessionId||sessionId;addMessage(data.answer||"I couldn't find enough information to answer that.","bot")}catch(err){addMessage("I couldn't reach the advisor. Please try again shortly.","bot");console.error(err)}finally{status.textContent=""}}
  launcher?.addEventListener("click",()=>{panel.classList.toggle("open");if(panel.classList.contains("open"))input.focus()});close?.addEventListener("click",()=>panel.classList.remove("open"));form?.addEventListener("submit",e=>{e.preventDefault();ask(input.value)});
  addMessage("Hi — I’m the 64 Squares Strategy advisor. Tell me what decision or team challenge you’re working on, and I’ll point you to the most relevant session or framework.","bot");addStarters();
})();
